{
 "title": "Database Connection Pool",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backend Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backend_db_active_connections_count{application = \"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Idle Connections Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "backend_db_idle_connections_count{application = \"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "backend_db_pool_size{application = \"$application\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Log Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Connections Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "log_db_active_connections_count{application = \"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Idle Connections Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "log_db_idle_connections_count{application = \"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "log_db_pool_size{application = \"$application\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}